
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: stairman7
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>
#include "Stairman.h"



static const uint8_t image_data_stairman7[96] = {
    // ∙∙∙∙∙∙████∙∙∙
    // ∙∙∙∙∙███████∙
    // ∙∙∙∙████████∙
    // ∙∙∙∙█████████
    // ∙∙∙██████████
    // ∙∙∙██████████
    // ∙∙∙∙█████████
    // ∙∙∙∙████████∙
    // ∙∙∙∙∙███████∙
    // ∙∙∙∙∙∙∙███∙∙∙
    // ∙∙∙∙∙∙███∙∙∙∙
    // ∙∙∙∙∙██████∙∙
    // ∙∙∙∙███████∙∙
    // ∙∙∙∙████████∙
    // ∙∙∙∙████████∙
    // ∙∙∙∙████████∙
    // ∙∙∙█████████∙
    // ∙∙∙████████∙∙
    // ∙∙∙████████∙∙
    // ∙∙█████████∙∙
    // ∙∙█████████∙∙
    // ∙∙█████████∙∙
    // ∙∙█████████∙∙
    // ∙██████████∙∙
    // ∙███████████∙
    // ∙███████████∙
    // █████████████
    // █████████∙███
    // ∙███████∙∙███
    // ∙████████∙███
    // ∙∙███████████
    // ∙∙∙██████████
    // ∙∙∙██████████
    // ∙∙∙████∙█████
    // ∙∙∙████∙∙████
    // ∙∙∙████∙∙████
    // ∙∙∙████∙∙████
    // ∙∙∙████∙∙████
    // ∙∙∙████∙∙████
    // ∙∙∙████∙█████
    // ∙∙█████∙████∙
    // ∙∙████∙∙████∙
    // ∙∙████∙∙████∙
    // ∙█████∙∙████∙
    // ∙████∙∙∙███∙∙
    // ∙████∙∙∙∙∙∙∙∙
    // ∙████∙∙∙∙∙∙∙∙
    // ∙████∙∙∙∙∙∙∙∙
    0x03, 0xc0, 
    0x07, 0xf0, 
    0x0f, 0xf0, 
    0x0f, 0xf8, 
    0x1f, 0xf8, 
    0x1f, 0xf8, 
    0x0f, 0xf8, 
    0x0f, 0xf0, 
    0x07, 0xf0, 
    0x01, 0xc0, 
    0x03, 0x80, 
    0x07, 0xe0, 
    0x0f, 0xe0, 
    0x0f, 0xf0, 
    0x0f, 0xf0, 
    0x0f, 0xf0, 
    0x1f, 0xf0, 
    0x1f, 0xe0, 
    0x1f, 0xe0, 
    0x3f, 0xe0, 
    0x3f, 0xe0, 
    0x3f, 0xe0, 
    0x3f, 0xe0, 
    0x7f, 0xe0, 
    0x7f, 0xf0, 
    0x7f, 0xf0, 
    0xff, 0xf8, 
    0xff, 0xb8, 
    0x7f, 0x38, 
    0x7f, 0xb8, 
    0x3f, 0xf8, 
    0x1f, 0xf8, 
    0x1f, 0xf8, 
    0x1e, 0xf8, 
    0x1e, 0x78, 
    0x1e, 0x78, 
    0x1e, 0x78, 
    0x1e, 0x78, 
    0x1e, 0x78, 
    0x1e, 0xf8, 
    0x3e, 0xf0, 
    0x3c, 0xf0, 
    0x3c, 0xf0, 
    0x7c, 0xf0, 
    0x78, 0xe0, 
    0x78, 0x00, 
    0x78, 0x00, 
    0x78, 0x00
};
const tImage stairman7 = { image_data_stairman7, 13, 48,
    8 };

